// Generated by gencpp from file i2cpwm_board/Servo.msg
// DO NOT EDIT!


#ifndef I2CPWM_BOARD_MESSAGE_SERVO_H
#define I2CPWM_BOARD_MESSAGE_SERVO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace i2cpwm_board
{
template <class ContainerAllocator>
struct Servo_
{
  typedef Servo_<ContainerAllocator> Type;

  Servo_()
    : servo(0)
    , value(0.0)  {
    }
  Servo_(const ContainerAllocator& _alloc)
    : servo(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _servo_type;
  _servo_type servo;

   typedef float _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::i2cpwm_board::Servo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::i2cpwm_board::Servo_<ContainerAllocator> const> ConstPtr;

}; // struct Servo_

typedef ::i2cpwm_board::Servo_<std::allocator<void> > Servo;

typedef boost::shared_ptr< ::i2cpwm_board::Servo > ServoPtr;
typedef boost::shared_ptr< ::i2cpwm_board::Servo const> ServoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::i2cpwm_board::Servo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::i2cpwm_board::Servo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace i2cpwm_board

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'i2cpwm_board': ['/home/ubuntu/catkin_ws/src/ros-i2cpwmboard/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::i2cpwm_board::Servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::i2cpwm_board::Servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::i2cpwm_board::Servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::i2cpwm_board::Servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::i2cpwm_board::Servo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::i2cpwm_board::Servo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::i2cpwm_board::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e89689ba58524f73da7d375fa49d8a1";
  }

  static const char* value(const ::i2cpwm_board::Servo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e89689ba58524f7ULL;
  static const uint64_t static_value2 = 0x3da7d375fa49d8a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::i2cpwm_board::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "i2cpwm_board/Servo";
  }

  static const char* value(const ::i2cpwm_board::Servo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::i2cpwm_board::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# the Servo message is commonly used message in this package to\n\
# assign a value to a specific servo. the purpose of the value is\n\
# dependent on the topic or service being called\n\
\n\
int16 servo\n\
float32 value\n\
";
  }

  static const char* value(const ::i2cpwm_board::Servo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::i2cpwm_board::Servo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Servo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::i2cpwm_board::Servo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::i2cpwm_board::Servo_<ContainerAllocator>& v)
  {
    s << indent << "servo: ";
    Printer<int16_t>::stream(s, indent + "  ", v.servo);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // I2CPWM_BOARD_MESSAGE_SERVO_H
